module.exports = {
  solutionsSidebar: [{ type: 'autogenerated', dirName: 'solutions' }],
  tricksSidebar: [{ type: 'autogenerated', dirName: 'tricks' }],
  aboutSidebar: [{ type: 'autogenerated', dirName: 'about' }],
};
