name: PR Checks
on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: "${{ secrets.REPO_ACCESS_TOKEN }}"