name: Dependency Update Checks
on: pull_request_target
jobs:
  build-test:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install && npm run build
  auto-approve:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: "${{ secrets.REPO_ACCESS_TOKEN }}"