name: PR Checks
on: [pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: "14"
      - run: npm ci --no-optional
      - run: npm run build
